"""create formulario and pergunta structure

Revision ID: a6690df04445
Revises: 
Create Date: 2025-08-04 22:09:00.614702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6690df04445'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formulario_id'), 'formulario', ['id'], unique=False)
    op.create_table('pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_formulario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('orientacao_resposta', sa.String(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('obrigatoria', sa.Boolean(), nullable=True),
    sa.Column('sub_pergunta', sa.Boolean(), nullable=True),
    sa.Column('tipo_pergunta', sa.Enum('BOOLEANO', 'MULTIPLA_ESCOLHA', 'UNICA_ESCOLHA', 'TEXTO_LIVRE', 'INTEIRO', 'DECIMAL', name='tipoperguntaenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_formulario'], ['formulario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pergunta_id'), 'pergunta', ['id'], unique=False)
    op.create_table('opcoes_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pergunta', sa.Integer(), nullable=False),
    sa.Column('resposta', sa.String(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('resposta_aberta', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_pergunta'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opcoes_respostas_id'), 'opcoes_respostas', ['id'], unique=False)
    op.create_table('opcoes_resposta_pergunta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_opcao_resposta', sa.Integer(), nullable=False),
    sa.Column('id_pergunta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_opcao_resposta'], ['opcoes_respostas.id'], ),
    sa.ForeignKeyConstraint(['id_pergunta'], ['pergunta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opcoes_resposta_pergunta_id'), 'opcoes_resposta_pergunta', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opcoes_resposta_pergunta_id'), table_name='opcoes_resposta_pergunta')
    op.drop_table('opcoes_resposta_pergunta')
    op.drop_index(op.f('ix_opcoes_respostas_id'), table_name='opcoes_respostas')
    op.drop_table('opcoes_respostas')
    op.drop_index(op.f('ix_pergunta_id'), table_name='pergunta')
    op.drop_table('pergunta')
    op.drop_index(op.f('ix_formulario_id'), table_name='formulario')
    op.drop_table('formulario')
    # ### end Alembic commands ###
